/* tslint:disable */
/* eslint-disable */
import { EnvironmentMode } from './environment-mode';
import { InvoiceThem } from './invoice-them';
export interface Branch {
  additionalStreetName?: null | string;
  address?: null | string;
  barCodeLength?: number;
  barCodeStart?: number;
  branchId?: number;
  branchLogo?: null | string;
  branchName?: null | string;
  branchSignature?: null | string;
  buildingNumber?: null | string;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  cityName?: null | string;
  citySubdivisionName?: null | string;
  commercialNo?: null | string;
  companyId?: number;
  companyName?: null | string;
  countrySubentity?: null | string;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  docRefGuid?: string;
  environmentMode?: EnvironmentMode;
  guid?: string;
  id?: number;
  industry?: null | string;
  invoiceThem?: InvoiceThem;
  isActive?: boolean;
  isUpdated?: boolean;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  nationalAddress?: null | string;
  no?: number;
  notes?: null | string;
  otp?: null | string;
  phoneNo?: null | string;
  plotIdentification?: null | string;
  postalBox?: null | string;
  postalZone?: null | string;
  priceLength?: number;
  priceSeparator?: number;
  priceStart?: number;
  qtyLength?: number;
  qtySeparator?: number;
  qtyStart?: number;
  registrationName?: null | string;
  roomNo?: null | string;
  schemeId?: null | string;
  sellingWithPricePolicy?: boolean;
  streetName?: null | string;
  taxNo?: null | string;
  tbL005ID?: number;
  transferWithPrice?: boolean;
  updatedCount?: number;
  zakatAuthority?: boolean;
}
