/* tslint:disable */
/* eslint-disable */
export interface BuyInvoiceDetails {
  bonus?: boolean;
  branchId?: number;
  branchName?: null | string;
  buyInvoiceId?: number;
  buyOfferOfferRow?: number;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  clientDesc?: number;
  color?: null | string;
  colorId?: number;
  companyId?: number;
  companyName?: null | string;
  correctQty?: number;
  correctWA?: number;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  discount?: number;
  discountPercent?: number;
  docDate?: string;
  docRefGuid?: string;
  extraDiscountAmount?: number;
  extraDiscountPer?: number;
  guid?: string;
  id?: number;
  isActive?: boolean;
  isCanceled?: boolean;
  isUpdated?: boolean;
  itemID?: number;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  no?: number;
  notes?: null | string;
  price?: number;
  productBarcode?: null | string;
  productCode?: null | string;
  productGroupGuid?: string;
  productGuide?: string;
  productId?: number;
  quantity?: number;
  returnedQty?: number;
  size?: number;
  tall?: number;
  totalDisc?: number;
  totalPrice?: number;
  totalPriceAfterDiscount?: number;
  totalPriceAfterVat?: number;
  unitDiscount?: number;
  uniteId?: number;
  updateFlag?: null | string;
  updatedCount?: number;
  vat?: number;
  vatAmount?: number;
  weight?: number;
  wide?: number;
}
