/* tslint:disable */
/* eslint-disable */
export interface FinanceSettings {
  allowedDiscAccount?: string;
  allowedDiscAccountCode?: null | string;
  allowedDiscAccountID?: number;
  allowedDiscAccountName?: null | string;
  bankAccount?: string;
  bankAccountCode?: null | string;
  bankAccountID?: number;
  bankAccountName?: null | string;
  branchId?: number;
  branchName?: null | string;
  buysAccount?: string;
  buysAccountCode?: null | string;
  buysAccountID?: number;
  buysAccountName?: null | string;
  buysReturnAccount?: string;
  buysReturnAccountCode?: null | string;
  buysReturnAccountID?: number;
  buysReturnAccountName?: null | string;
  buysVatAccount?: string;
  buysVatAccountCode?: null | string;
  buysVatAccountID?: number;
  buysVatAccountName?: null | string;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  clientsAccount?: string;
  clientsAccountCode?: null | string;
  clientsAccountID?: number;
  clientsAccountName?: null | string;
  companyId?: number;
  companyName?: null | string;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  docRefGuid?: string;
  earnedDiscAccount?: string;
  earnedDiscAccountCode?: null | string;
  earnedDiscAccountID?: number;
  earnedDiscAccountName?: null | string;
  guid?: string;
  id?: number;
  isActive?: boolean;
  isCanceled?: boolean;
  isUpdated?: boolean;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  no?: number;
  notes?: null | string;
  salesAccount?: string;
  salesAccountCode?: null | string;
  salesAccountID?: number;
  salesAccountName?: null | string;
  salesReturnAccount?: string;
  salesReturnAccountCode?: null | string;
  salesReturnAccountID?: number;
  salesReturnAccountName?: null | string;
  storageTransferAccount?: string;
  storageTransferAccountCode?: null | string;
  storageTransferAccountID?: number;
  storageTransferAccountName?: null | string;
  supplierAccount?: string;
  supplierAccountCode?: null | string;
  supplierAccountID?: number;
  supplierAccountName?: null | string;
  treasuryCashAccount?: string;
  treasuryCashAccountCode?: null | string;
  treasuryCashAccountID?: number;
  treasuryCashAccountName?: null | string;
  updateFlag?: null | string;
  updatedCount?: number;
  vatAccount?: string;
  vatAccountCode?: null | string;
  vatAccountID?: number;
  vatAccountName?: null | string;
}
