/* tslint:disable */
/* eslint-disable */
import { ItemPlace } from './item-place';
import { ItemType } from './item-type';
import { ItemUnit } from './item-unit';
export interface Item {
  balance?: number;
  branchId?: number;
  branchName?: null | string;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  cardImage?: null | string;
  category?: string;
  choseUnite?: null | string;
  code?: null | string;
  companyId?: number;
  companyName?: null | string;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  description?: null | string;
  descriptionNotes?: null | string;
  discountTax?: number;
  docRefGuid?: string;
  expiryDateRequired?: boolean;
  greatestQuantity?: number;
  groupGuid?: string;
  guid?: string;
  howToUse?: null | string;
  id?: number;
  imeges?: null | Blob;
  isActive?: boolean;
  isUpdated?: boolean;
  itemGroupCode?: null | string;
  itemGroupGuid?: string;
  itemGroupId?: number;
  itemPlace?: ItemPlace;
  itemUnits?: null | Array<ItemUnit>;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  lessQuantity?: number;
  maxLimit?: number;
  minLimit?: number;
  model?: null | string;
  modelType?: null | string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  no?: number;
  notDiscountable?: boolean;
  notTaxable?: boolean;
  notes?: null | string;
  opinions?: null | string;
  orderLimit?: number;
  productCompany?: null | string;
  productDescription?: null | string;
  profitRate?: number;
  serialNo?: number;
  smallestUnit?: number;
  specifications?: null | string;
  tbL007ID?: number;
  totalInQty?: number;
  totalOutQty?: number;
  type?: ItemType;
  typeOfProfit?: number;
  updateFlag?: null | string;
  updatedCount?: number;
  valueOfProfit?: number;
  vat?: number;
}
