/* tslint:disable */
/* eslint-disable */
import { ClientType } from './client-type';
import { DocType } from './doc-type';
import { PaymentType } from './payment-type';
import { SaleInvNotes } from './sale-inv-notes';
import { SaleInvoiceDepts } from './sale-invoice-depts';
import { SaleInvoiceDetails } from './sale-invoice-details';
import { SaleRatingNotes } from './sale-rating-notes';
export interface SaleInvoice {
  bankGuid?: string;
  bankId?: number;
  bankName?: null | string;
  branchId?: number;
  branchName?: null | string;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  cash?: number;
  clientGuid?: string;
  clientId?: number;
  clientName?: null | string;
  clientType?: ClientType;
  companyId?: number;
  companyName?: null | string;
  costCenterGuid?: string;
  costCenterId?: number;
  costCenterName?: null | string;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  debt?: number;
  docDate?: string;
  docGuid?: string;
  docNo?: number;
  docProjectId?: number;
  docProjectName?: null | string;
  docRefGuid?: string;
  docType?: DocType;
  extraDisc?: number;
  guid?: string;
  id?: number;
  isActive?: boolean;
  isCanceled?: boolean;
  isUpdated?: boolean;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  no?: number;
  notes?: null | string;
  paymentType?: PaymentType;
  pricePolicyId?: number;
  pricePolicyName?: null | string;
  qrCode?: null | string;
  report?: null | string;
  saleInvNotes?: null | Array<SaleInvNotes>;
  saleInvoiceDepts?: null | Array<SaleInvoiceDepts>;
  saleInvoiceDetails?: null | Array<SaleInvoiceDetails>;
  saleInvoiceURLFile?: null | string;
  saleOfferId?: number;
  saleRatingNotes?: null | Array<SaleRatingNotes>;
  salesManId?: number;
  salesManName?: null | string;
  shiftId?: number;
  storeGuid?: string;
  storeId?: number;
  storeName?: null | string;
  tbL022ID?: number;
  totalDisc?: number;
  totalDiscRate?: number;
  totalDiscafterVat?: number;
  totalInvoice?: number;
  totalInvoiceAfterDisc?: number;
  totalInvoiceAfterVat?: number;
  totalInvoiceDu?: number;
  totalInvoiceGross?: number;
  totalInvoiceVatAmount?: number;
  totalSaleDepts?: number;
  totalVatRate?: number;
  treasuryId?: number;
  updateFlag?: null | string;
  updatedCount?: number;
  userId?: string;
  uuid?: null | string;
  visa?: number;
}
