/* tslint:disable */
/* eslint-disable */
export interface StorageOpenDetailsDto {
  branchId?: number;
  branchName?: null | string;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  companyId?: number;
  companyName?: null | string;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  discount?: number;
  docRefGuid?: string;
  extraDiscountAmount?: number;
  extraDiscountPer?: number;
  guid?: string;
  id?: number;
  isActive?: boolean;
  isUpdated?: boolean;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  no?: number;
  notes?: null | string;
  price?: number;
  productBarcode?: null | string;
  productCode?: null | string;
  productGroupGuid?: string;
  productGuide?: string;
  productId?: number;
  qty?: number;
  quantity?: number;
  returnedQty?: number;
  total?: number;
  totalDisc?: number;
  totalPrice?: number;
  totalPriceAfterDiscount?: number;
  totalPriceAfterVat?: number;
  unitDiscount?: number;
  unitId?: number;
  unitName?: null | string;
  updatedCount?: number;
  vat?: number;
  vatAmount?: number;
}
