/* tslint:disable */
/* eslint-disable */
export interface Supplier {
  address?: null | string;
  area?: null | string;
  areaId?: number;
  branch?: null | string;
  branchId?: number;
  branchName?: null | string;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  commercialNo?: null | string;
  companyId?: number;
  companyName?: null | string;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  debt?: number;
  defaultDiscPer?: number;
  discountPercentage?: number;
  docRefGuid?: string;
  email?: null | string;
  faceBook?: null | string;
  firstTransaction?: string;
  forwardSale?: null | string;
  forwardSaleId?: number;
  guid?: string;
  handlingStatus?: null | string;
  handlingStatusId?: number;
  id?: number;
  isActive?: boolean;
  isUpdated?: boolean;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  mobile1?: null | string;
  mobile2?: null | string;
  mobile3?: null | string;
  mobile4?: null | string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  nationalId?: number;
  no?: number;
  notes?: null | string;
  notesOfCritedConditions?: null | string;
  numberOfCritedDayes?: number;
  paymentCount?: number;
  phone1?: null | string;
  phone2?: null | string;
  phone3?: null | string;
  phone4?: null | string;
  phoneNo?: null | string;
  priceType?: null | string;
  priceTypeId?: number;
  privateCoding?: null | string;
  representative?: null | string;
  representativeId?: number;
  suppliersClassification?: null | string;
  suppliersClassificationId?: number;
  suppliersGroup?: null | string;
  suppliersGroupId?: number;
  taxNo?: null | string;
  tbL016ID?: number;
  totalCash?: number;
  totalDebt?: number;
  totalSales?: number;
  updateFlag?: null | string;
  updatedCount?: number;
  webSite?: null | string;
  whatsApp?: null | string;
}
