/* tslint:disable */
/* eslint-disable */
export interface TreasuryTransactionDetail {
  accTreeCode?: number;
  accTreeId?: number;
  accTreeName?: null | string;
  amount?: number;
  bankAccountNo?: null | string;
  bankId?: number;
  bankName?: null | string;
  branchId?: number;
  branchName?: null | string;
  buyInvoiceId?: number;
  cancelBy?: null | string;
  cancelById?: number;
  cancelDate?: string;
  clientId?: number;
  clientName?: null | string;
  companyId?: number;
  companyName?: null | string;
  costCenterId?: number;
  costCenterName?: null | string;
  createById?: null | string;
  createByName?: null | string;
  createdDate?: string;
  docClassificationId?: number;
  docClassificationName?: null | string;
  docProjectsId?: number;
  docProjectsName?: null | string;
  docRefGuid?: string;
  guid?: string;
  id?: number;
  isActive?: boolean;
  isCanceled?: boolean;
  isUpdated?: boolean;
  isVatchecked?: boolean;
  isVatcheckedNotes?: null | string;
  lastModifiedDate?: string;
  lastUpdatedBy?: null | string;
  lastUpdatedDate?: string;
  modifyById?: null | string;
  modifyByName?: null | string;
  modifyCount?: number;
  nameAr?: null | string;
  nameEn?: null | string;
  no?: number;
  notes?: null | string;
  saleInvoiceId?: number;
  supplierId?: number;
  supplierName?: null | string;
  treasuryId?: number;
  treasuryName?: null | string;
  updateFlag?: null | string;
  updatedCount?: number;
  vatVal?: number;
}
